INSERT INTO prodpol.product_descriptions (product_id, language_code, title, body, is_public)
VALUES 
    (2, 'en', 'Test Product', 'This is a description for the test product.', true),
    (2, 'pl', 'Produkt Testowy', 'To jest opis produktu testowego.', true),
    (3, 'en', 'Super Gadget', 'A super gadget that solves all your problems.', true),
    (3, 'pl', 'Super Gadżet', 'Super gadżet, który rozwiąże wszystkie Twoje problemy.', true),
    (4, 'en', 'Mega Widget', 'The most powerful widget on the market.', true),
    (4, 'pl', 'Mega Widżet', 'Najpotężniejszy widżet na rynku.', true),
    (10, 'en', 'Screw M8x20', 'Stainless steel screw, M8 thread, 20mm length.', true),
    (10, 'pl', 'Śruba M8x20', 'Śruba ze stali nierdzewnej, gwint M8, długość 20mm.', true),
    (11, 'en', 'Screw M10x30', 'Stainless steel screw, M10 thread, 30mm length.', true),
    (11, 'pl', 'Śruba M10x30', 'Śruba ze stali nierdzewnej, gwint M10, długość 30mm.', true),
    (12, 'en', 'Steel Sheet 2mm', 'Hot-rolled steel sheet, 2mm thickness.', true),
    (12, 'pl', 'Blacha Stalowa 2mm', 'Blacha stalowa walcowana na gorąco, grubość 2mm.', true),
    (13, 'en', 'Steel Sheet 5mm', 'Hot-rolled steel sheet, 5mm thickness.', true),
    (13, 'pl', 'Blacha Stalowa 5mm', 'Blacha stalowa walcowana na gorąco, grubość 5mm.', true),
    (14, 'en', 'Aluminum Profile 40x40', 'Anodized aluminum profile, 40x40mm.', true),
    (14, 'pl', 'Profil Aluminiowy 40x40', 'Profil aluminiowy anodowany, 40x40mm.', true),
    (15, 'en', 'Aluminum Profile 80x80', 'Anodized aluminum profile, 80x80mm.', true),
    (15, 'pl', 'Profil Aluminiowy 80x80', 'Profil aluminiowy anodowany, 80x80mm.', true),
    (16, 'en', 'Washer M8', 'Flat washer for M8 screws.', true),
    (16, 'pl', 'Podkładka M8', 'Podkładka płaska do śrub M8.', true),
    (17, 'en', 'Nut M8', 'Hexagonal nut for M8 screws.', true),
    (17, 'pl', 'Nakrętka M8', 'Nakrętka sześciokątna do śrub M8.', true),
    (18, 'en', 'Large Cardboard Box', 'Heavy-duty cardboard box for shipping.', true),
    (18, 'pl', 'Duże Pudełko Kartonowe', 'Wytrzymałe pudełko kartonowe do wysyłki.', true),
    (19, 'en', 'Packing Tape', 'Strong adhesive packing tape.', true),
    (19, 'pl', 'Taśma Pakowa', 'Mocna klejąca taśma pakowa.', true),
    (20, 'en', 'Premium Engraving Service', 'High-precision laser engraving service.', true),
    (20, 'pl', 'Usługa Grawerowania Premium', 'Usługa precyzyjnego grawerowania laserowego.', true),
    (21, 'en', 'Copper Pipe 15mm', 'Seamless copper pipe, 15mm diameter.', true),
    (21, 'pl', 'Rura Miedziana 15mm', 'Rura miedziana bezszwowa, średnica 15mm.', true),
    (22, 'en', 'Chemical Cleaner 1L', 'Industrial grade chemical cleaner.', true),
    (22, 'pl', 'Środek Chemiczny 1L', 'Przemysłowy środek czyszczący.', true),
    (23, 'en', 'Starter Kit Bundle', 'A complete starter kit with various components.', true),
    (23, 'pl', 'Zestaw Startowy', 'Kompletny zestaw startowy z różnymi komponentami.', true),
    (24, 'en', 'Steel Rod 10mm', 'Solid steel rod, 10mm diameter.', true),
    (24, 'pl', 'Pręt Stalowy 10mm', 'Solidny pręt stalowy, średnica 10mm.', true)
ON CONFLICT DO NOTHING;
